// Code generated by "stringer -type=APIVersion"; DO NOT EDIT.

package apiversions

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[V2-0]
	_ = x[V3-1]
	_ = x[UnknownVersion-2]
}

const _APIVersion_name = "V2V3UnknownVersion"

var _APIVersion_index = [...]uint8{0, 2, 4, 18}

func (i APIVersion) String() string {
	if i < 0 || i >= APIVersion(len(_APIVersion_index)-1) {
		return "APIVersion(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _APIVersion_name[_APIVersion_index[i]:_APIVersion_index[i+1]]
}
